import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'
import 'remixicon/fonts/remixicon.css'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import { ScreenStatusProvider } from './contexts/ScreeStatusContext'

const open_sans = Open_Sans({
  weight: ['400', '600', '800'],
  subsets: ['latin'],
  variable: '--font-open-sans',
})

export const metadata: Metadata = {
  title: 'Flick',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <ScreenStatusProvider>{children}</ScreenStatusProvider>
        <SpeedInsights />
      </body>
    </html>
  )
}
